config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  get 'sessions/new'

  post 'sessions/create'

  get 'sessions/destroy'

  resources :users

  root 'home#index'

  get 'home/index'

  get 'home/about'

  get 'recipies/index'

  get 'recipies/rvm'

  get 'how_to/instalation'

  get 'how_to/hello_world'

  get 'how_to/index'

  get 'how_to/statiske_sider'

  
  namespace :admin do
    resources :pages
    resources :admins
    resources :subjects
  end
end

app/models/admin_page.rb
class AdminPage < ApplicationRecord
  belongs_to :admin_subject
	validates :headder, presence: true
	validates :headder, length: { maximum: 50 }
	validates :content, presence: true

end

app/models/admin_subject.rb
class AdminSubject < ApplicationRecord
  has_many :admin_pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  after_create :default_role

  validates :username, 
            presence: true,
            uniqueness: true,
            length: { maximum: 30 }

  validates :email,
            presence: true,
            uniqueness: true,
            length: { maximum: 30 }

  validates :password,
            length: {minimum: 5}


  def default_role
    self.role = "student"
    save!
  end
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController

  def index
    @page = AdminPage.all
  end

  def new
    @admin_subjects = AdminSubject.all
    @page = AdminPage.new
  end

  def create
    @page = AdminPage.create(admin_page_params)
    @page.save
    redirect_to how_to_index_path
  end

  def show
    @page = AdminPage.find(params[:id])
    filler = @page
    @headder = filler.headder
    @content = filler.content
  end

  def edit
    @page = AdminPage.find(params[:id])
  end

  def update
    @page = AdminPage.find(params[:id])
    @page.update(admin_page_params)
    redirect_to admin_pages_path
  end

  def destroy
    @page = AdminPage.find(params[:id])
    @page.destroy
    redirect_to admin_pages_path
  end

  private

  def admin_page_params
    params.require(:admin_page).permit(:content,:headder,:admin_subject_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

	def about
		@about_title = AboutContent.first.title
		@about_content = AboutContent.first.text
	end
end

app/controllers/how_to_controller.rb
class HowToController < ApplicationController

	def index
		@admin_subject = AdminSubject.all
	end

	def instalation
	end

	def hello_world
	end

	def statiske_sider
	end

end

app/controllers/recipies_controller.rb
class RecipiesController < ApplicationController
  def index
  end

  def instalation
  end

  def rvm
  end

  def hello_world
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to home_index_path
  		flash[:success] = "du er nu logget ind"
  	else 
  		redirect_to sessions_new_path
  		flash[:success] = "fejl i email eller kodeord"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to home_index_path
  	flash[:success] = "du er nu logget ud"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @users = User.new
  end

  def create
    @user = User.create(user_params)
    if  @user.save
      session[:user_id] = @user.id
      redirect_to home_index_path
      flash[:success] = "brugeren er oprettet"
    else 
      redirect_to new_users_path
      flash[:danger] = "fejl i brugernavn, email eller password"
    end
  end

  def show
    @users = User.find(params[:id])
  end

  def edit
    @users = User.find(params[:id])
  end

  def update
    @users = User.find(params[:id])
    @users.update(user_params)
    redirect_to users_path
  end

  def destroy
    @users = User.find(params[:id])
    @users.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/how_to_helper.rb
module HowToHelper
end

app/helpers/recipies_helper.rb
module RecipiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/pages/_form.html.erb
<%= form_for @page do |f| %>
  <%= f.label :vælg_emne %>
  <br>
  <%= f.collection_select(:admin_subject_id, @admin_subjects, :id,:name ) %>
  <br>
  <%= f.label :headder %>
  <br>
  <%= f.text_field :headder %>
  <br>
  <%= f.label :content %>
  <br>
  <%= f.cktext_area :content, class: "ckeditor" %>
  <br>
  <br>
  <%= f.submit " tilføj side " %>
<% end %>
<%= link_to " Tilbage ", admin_pages_path %>

app/views/admin/pages/edit.html.erb
<% if current_user && current_user.role == "admin" || "teacher" %>
	<h1>Rediger side</h1>
	<%= render "form" %>
<% else %>
	<h1>Desværre!</h1>
	<h5>Du har desverre ikke bruger rettigheder til denne side </h5>
	<%= link_to "hjem", home_index_path %>
<% end %>

app/views/admin/pages/index.html.erb
<% if current_user && current_user.role == "admin" || "teacher"%>
	<% @page.each do |page| %>
		<br>
		<h4><%= page.headder %></h4>
		<%= link_to " vis ", page %>
		<%= link_to " Rediger ", edit_admin_page_path(page)%>
		<%= link_to " Slet ", page, method: :delete, data:{confirm: "er du sikker på at du vil slette siden?"} %>
	<% end %>
	<br>
	<br>
	<%= link_to "Ny Side", new_admin_page_path %>
<% else %>
	<h1>Desværre!</h1>
	<h5>Du har desverre ikke bruger rettigheder til denne side </h5>
	<%= link_to "hjem", home_index_path %>
<% end %>

app/views/admin/pages/new.html.erb
<% if current_user && current_user.role == "teacher" || "admin" %>
	<h1>New!... Motherfucker!!!!</h1>
	<%= render "form" %>
<% else %>
	<h1>Desværre!</h1>
	<h5>Du har desverre ikke bruger rettigheder til denne side </h5>
	<%= link_to "hjem", home_index_path %>
<% end %>

app/views/admin/pages/show.html.erb
<h1> <%= @headder.to_s.html_safe %> </h1>
<br>
<p> <%= @content.to_s.html_safe %> </p>
<br>
<br>
<%= link_to "Tilbage", admin_pages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCookBook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   </head>


  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%=link_to "Home", home_index_path %></li>
            <li><%= link_to "Opskrifter", recipies_index_path%></li>
            <li><%= link_to "How to", how_to_index_path%></li>
            <li><%= link_to "about", home_about_path%></li>
          </ul>
          <ul class="nav navbar-nav">
            <% if current_user %>
              <% if current_user.role == "admin" || "teacher" %>
                <li><%= link_to "Ny side", new_admin_page_path %></li>
                <li><%= link_to "Nyt Emne", new_admin_subject_path %></li>
              <% end %>
              <li><%= link_to "Log ud", sessions_destroy_path %></li>
            <% else %>
             <li><%= link_to 'Log ind', sessions_new_path %></li>
             <li><%= link_to "Opret bruger", new_user_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container", style="margin-top: 200px;">
			<%= yield %>
      
    </div><!-- /.container -->


  </body>
  <footer class="footer">
      <div class="container">
        <p class="text-muted"></p>
      </div>
  </footer>
</html>

app/views/shared/_how_to_links.html.erb
<%=link_to "INSTALATION", how_to_instalation_path, class: "btn btn-danger"%>

<%=link_to "HELLO WORLD", how_to_hello_world_path, class: "btn btn-danger"%>

<%=link_to "STATISKE SIDER", how_to_statiske_sider_path, class: "btn btn-danger"%>

app/views/shared/_recipies_links.html.erb
<%=link_to "RVM", recipies_rvm_path, class: "btn btn-danger"%>